### ISSUE TITLE
Feature request: Ignore sidebar/excessive screen padding

### ISSUE THREAD

**Issue by tbirrell** [chintown/monocle#13]
As you can see in the screenshot, the actual page content is unnecessarily minimized in the minimap. I recognize this would be more of a power-user feature, but would it be possible to specify selectors on a per-url basis instead of universally using `document.body`?

![screenshot-laravel com-2019 08 20-11_20_14](https://user-images.githubusercontent.com/17275888/63365239-e17c8900-c33c-11e9-83b1-22ecbc90f254.png)

**Comment by chintown** [comment]
Hi @tbirrell, 

This is an interesting idea. I appreciate the further thinking.

The preview is deliberately generated in the exact ratio of the _viewport_ (you can try to resize the browser window and you will see a corresponding _refresh_). By keeping the ratio matched, it's guaranteed that the page moves to the exact point while you make a click-to-jump with the magnifier. 

If the preview only reflects a narrowed area, we can force the scrolling to be roughly synced, however, the overall user experience (i.e. accuracy) will be impacted, which is a major concern to me. (Also, in a case that the main content is shorter than the page, the maximum scrollable distance would be off from the original page.)

Alternatively, you can increase the width of preview panel so you get more visual hints. Also, the magnifier is designed to have a finer navigational preview with mouse. Do they help in your usecase? Or they are too limited in certain ways?

**Comment by tbirrell** [comment]
I suppose that makes sense. I can understand why you made the design decision you did. While not terribly helpful in my case, I can appreciate the technical hurdles that are in the way. I hadn't thought about how it would effect scrolling.

**Comment by tbirrell** [comment]
Actually, after tinkering around a bit, I think you'd be surprised how well it works. The scroll is mapping really well. I've run into some issues with the canvas being weird, but if you want to take a look at it, I'd be happy to share the code with you.

**Comment by tbirrell** [comment]
![image](https://user-images.githubusercontent.com/17275888/63446047-1f41e600-c3ff-11e9-8ee4-65589f844751.png)

**Comment by chintown** [comment]
So the glitch of canvas rendering is one thing. But more importantly, a predictable scrolling is the core functionality of the tool. By changing the target from a whole page to a selected area, in different cases, the scrolling is inaccurate or even not working.

#### accuracy

When user clicks the preview, the viewport should be scrolled to the place where the click point is centered in the viewport. If we simply change the reference from `document.body` to a selected dom, the scroll offset will be quite off.

#### predictable scrolling

If the selected content is relatively short against to the whole page (or shorter than the viewport height) and we change the target content from `document.body` to the selected dom, that means the scrollable distance of the preview area will be shorter than the scrollable distance of the page, making the two scrolling out of sync (or the preview won't scroll at all).

I see the need of reducing distractions but I also want to keep the tool consistent and predictable. If a feature requires users to deeply understand the details and potential risks, I would take a further thought. On the other hand, do you feel the mouse operation (with the magnifier) is too tedious to help you to take a finer control?

**Comment by tbirrell** [comment]
In my experience, the preview mapped to the click-scroll spot on. So I'm not entirely sure what you mean about the accuracy being off. I can understand the potential confusion of scrolling to the bottom of the preview and not being at the bottom of the page though.

As for the feature, given that it would be in advanced settings, require the user to manually set, as well as have a working knowledge of CSS selectors, I don't think that it is unreasonable to assume they'll understand whats going on.

The issue I have with the magnifying is that its claustrophobic due to the `border-radius`. That may just be a personal thing, but the 300px box does a weird thing to the crop that loses the right-hand side of the page after like 1200px or something.

**Comment by chintown** [comment]
> the scroll offset will be quite off.

Here's an example of the accuracy issue (it might be mitigated to be less observable if the target content is long). Note that the expected behavior is — the gray area should centered at the click point.

|before|after|
-------|-----
| ![scroll02](https://user-images.githubusercontent.com/119000/63651556-c8902100-c70a-11e9-8028-03c950482947.gif) | ![scroll01](https://user-images.githubusercontent.com/119000/63651555-c332d680-c70a-11e9-9dbe-5f1241d158eb.gif) |

> requires users to deeply understand the details and potential risks

It's more about the potential change in overall user experience like we discussed here (e.g. unsynced scrolling) rather than the selector settings.

> the 300px box does a weird thing to the crop that loses the right-hand side of the page after like 1200px or something.

Do you mean it stops showing preview, the preview is inaccurate or it's just hard to know where it is?

**Comment by tbirrell** [comment]
Oh, I see what you are talking about. The Laravel header (where I've been testing) was short enough that I didn't notice the offset.

Thanks for entertaining the idea even if it didn't work out.
