### ISSUE TITLE
Reload snapshot on DOM change

### ISSUE THREAD

**Issue by Yodzorah** [chintown/monocle#4]
The map doesn't reload itself after page was changed. It's critical for sites using scrolling pagination - when you scrolled page down and new content loaded, the map still has its initial height, so you can't scroll down with it. Futhermore, it doesn't work properly with `position: fixed` elements.

[For example.](https://duckduckgo.com/?q=scroll+down%2C+click+"More"+and+watch+the+map&t=vivaldi) Look at the fixed button in the bottom right corner, it's not where the map says it is - it's on its place only in initial scroll position (when scroll from top = 0).

**Comment by chintown** [comment]
Hi @Yodzorah , thanks for reaching out! I appreciate you've provided clear example and instructions to reproduce the issue.

The short answer is — there _is_ some limitation from the tool. It's good for article-based static webpage. But it's not a good fit for pages with dynamic content.

More details about the limitation — webpages could be dynamically changed in various ways. It's nearly impossible to keep eyes on all the changes. Or the cost is prohibitively high which eventually impairs your browsing experience. It's a trade-off I chose to not support dynamic content.

I'm resolving this as wont-fix. But I think the issue itself is still valuable. I will put this into Q&A.

**Comment by Yodzorah** [comment]
@chintown, did you consider [html2canvas](http://html2canvas.hertzen.com/) lib?  It's pretty fast, and a small time ago [these guys](https://www.magnoliyan.com/mini-map/) used it for the same purpose (now it's broken, but it's very recent change, I belive it can be fixed). They redraw page often, and it costed almost nothing even on very long pages.

So, maybe there's an option with adding the third way of drawing the map?
