### ISSUE TITLE
Enable zoomed view for the whole map

### ISSUE THREAD

**Issue by Yodzorah** [chintown/monocle#5]
Zoomed view is useful, because you can look at the page preview and at the same time look into its full-size pieces. So, when you're working with the map, you expect these pieces will be shown for whatever area you choose. You don't look at the map and at the visible page part (at the actual page) at the same time. For now I can only check one piece of the map (like, "what is thing to the bottom of the page"), but I can't look around with that zoom feature (e.g., just walk with this zoom view through the whole map and intuitively get what's going on on the page).

And another thing about that. When user enables zoomed view feature - "Show a zoomed view while mouse hovers on scroll preview" - he understands that not as "when event was invoked", but as "whenever the mouse is on scroll preview". So, when you're dragging the map's view, you expect, zoomed view will change, too, because you're moving cursor over the map while dragging, you're setting a new point for zoom feature to display from.

**Comment by chintown** [comment]
To the first question

>I can't look around with that zoom feature (e.g., just walk with this zoom view through the whole map and intuitively get what's going on on the page). 

I thought it's an existing feature or I may misunderstand you question. But please check this screen recording.

![preview-in-moving](https://user-images.githubusercontent.com/119000/38160787-c40f9c04-3477-11e8-9727-66292bd65fc7.gif)

Btw, I notice sometimes it looks pretty janky and delayed. That's the performance challenge I haven't resolved yet.

**Comment by chintown** [comment]
To the second question

> So, when you're dragging the map's view, you expect, zoomed view will change, too.

I think that's something I could improve.

To me, when I'm dragging the map's view, I actually use it as a scrollbar, a giant one. And I just keep eyes one the original page rather than the zoomed view (aka magnifier).

**Comment by Yodzorah** [comment]
@chintown,

1. Try to continue zoom survey through the current area of the page. You're zooming something under the map "thumb", then moving up through the visible area of page and this is where the zoom view stops. It seems logical, because you're seeing the visible part of the page full-sized without map and you have no need to zoom it in the map, but it's not comfortable, neither intuitive - you expect a "survey map" feature will allow you to survey the whole map. Without ability to zoom the "thumb" area, the whole "looking around" eventually turns into "hover the spot and see what's there", because intuitively you don't have the whole map, you have the two pieces of it: "before the thumb" and "after the thumb"; technically, there is almost no difference, but with the whole map available for zoom you think of the zoom view as a "map browser" and try to use it so, and without it you think of it as an array of spots available for zooming with an ability to browse inside these separated spots.

2. It's, actually, one suggestion, because the second part specifies the map's behavior on dragging in case the first part will be accepted. So, the whole point is about "do zoom view work for visible area, too")

**Comment by chintown** [comment]
The main issue has been fixed in latest version (4.1). And I simply hide the magnifier/zoomer while page is scrolling to make it less distracting.
