### ISSUE TITLE
Ability to disable Auto-Hide

### ISSUE THREAD

**Issue by Yodzorah** [chintown/monocle#6]
For me it's really not comfortable when it constantly hides, though some users really need Auto-Hide feature. Additional checkbox "Enable" would satisfy both sides.

**Comment by chintown** [comment]
Right, it could be a bit annoying.

The quick workaround is 

1. Go to Options page ( **chrome-extension://hhpfdnhklmhheldplcmfhfdooeekgpmm/options/options.html#advanced** )
2. In **Auto-hide** section, change the delay to a long time. For example, **86400** seconds (1 day).

With that, the tool will try to wait for a long time before hiding itself. 

I will consider to make the setting more intuitive as you suggested.

**Comment by chintown** [comment]
I'm going to close the issue as a workaround has been provided. Considering different users have different preferences; some people is fine to have a sticky preview while other thinks it's annoying, a delayed auto-hide gives us more flexibility. 

Feel free to reopen if you think having a disable option is still critical.
